import { Metadata } from "next";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "../trpc/client";
import { Toaster } from "../components/ui/sonner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Bee-Pai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body
          className={`${inter.className} antialiased`}
        >
          <Toaster />
          {children}
        </body>
      </html>
    </TRPCReactProvider>
  );
}
